### ISSUE TITLE
Remove "Development Iteration" and "#" number prefix from Milestones...

### ISSUE THREAD

**Issue by jadjare** [dibley1973/OpenRMS#12]
Remove the standard prefix from the "Development Iteration" Milestones.  It is hard to distinguish one from the other in the issues overview screen or individual issue screen, as all milestones are abbreviated to "Development Itera..."

/cc @dibley1973 @johncollinson2001 
Please comment if you're not happy with the naming change and I'll revert the milestone names back to the previous convention.

**Comment by dibley1973** [comment]
Fine by me. :+1:
