### ISSUE TITLE
Changing properties via setters or ChangeX() methods?

### ISSUE THREAD

**Issue by johncollinson2001** [dibley1973/OpenRMS#14]
**entity.ChangeX("value")** or **entity.X = "value"**

I think I'm falling on the side of using the setters... but using setters mean no auto-implemented properties. Must define private members. Of course you save on having to type a method for every value you want to change.

Any thoughts?

**Comment by jadjare** [comment]
I'm definitely for setting properties via methods.  The main reason for this is to better express the language of the domain.  Given the intent is to express the domain language it wouldn't always be the case that methods would be called Change(), thus concepts such as:
```
product.UpdateDescriptionTo("funky top")
product.MarkAsActive()
```
...Read better than
```
product.Description="funky top"
product.IsActive=true
```

Also, if EF or another mapping tool binds directly to the entity it can stop unnecessary guards, validation and actions happening during the binding process.  This latter point may be another discussion for later, a la state objects to protect ORM frameworks from interfering with the domain - see https://vaughnvernon.co/?p=879 , but this topic can be discussed as or when it becomes a problem.

**Comment by dibley1973** [comment]
Like Joseph's example, I'd like to see "setting methods" that are named to explicitly describe what data they are mutating and if possible in the language of the domain.

I do struggle to come up with the right wording more often than not, but if the method is there, refactoring the name to be more meaningful should not be a problem, except the _pain_ of refactoring the unit tests that test it!

I know auto implemented properties are fast to write, but I think in _this_ product if we do get it off the ground then well thought out* robust code is much more important that quick to write code.

*yes I may struggle with that with my "lets write more code ethic"!

**Comment by johncollinson2001** [comment]
OK that's all fine - all up for nicely named expressive code.

Correct me if I'm wrong, but in an ideal world we'd end up with a private member, a public get (via a property) and a custom set method? 

However I believe we're required by certain external components (ok - I'm talking about ef) to have property setters - albiet private. Will these just call through to the custom setters?

In my head entity.X = is pretty self explanatory - you're changing X. Having a separately named method isn't needed, but I don't really care too much either way here and guess I lean towards your way of thinking now you've explained it. But having a property setter as well, just for an external component seems like an evil, so adopting setters to change values gets around this (with the argument that were forced down a route for the needs of an external component).

I used to think having to define gets/sets separately in Java was a pain in the ass - now I'm wondering if it is infact c# auto implemented properties which is the pain!

**Comment by jadjare** [comment]
Q: "However I believe we're required by certain external components (ok - I'm talking about ef) to have property setters - albiet private. Will these just call through to the custom setters?"
A: In my opinion private setters would not call through to the customer setter methods.  If EF is to bind directly to the entity I don't believe you'd want the custom setters to be called.  Restoring the state of an entity is not the same as updating a description.  Also, I think you'd accept that the data coming back from the persistence store is valid.

To extend this point, for example, the UpdateDescriptionTo("Funky Top") may be implemented something like this:
``` csharp
public class Product {
    public string Description {get; private set;} //Not property definition can still use auto implemented syntax
    public void UpdateDescriptionTo(string newDescription)
    {
        if(newDescription==null) throw new ArgumentNullException(nameof(newDescription));

        this.Description = newDescription        
        DomainEvent.Publish(new ProductDescriptionUpdatedEvent(this.Id, newDescription));

    }
}
```
In this instance you wouldn't want all that gubbins firing when restoring the state of an entity.

Another good way to avoid having to thing about all these mechanics and separate out the problem of ORM tools interfering with the design of the domain is to use a backing State object as per the previously linked Vernon Vaughn article and what Duane is looking at.


Q: "In my head entity.X = is pretty self explanatory - you're changing X."
A: "This is true, but it's unlikely to follow the Ubiquitous Language.  You're unlikely to hear a customer say, 'I want to set the product's description equal to 'funky top'', you're more likely to hear 'I want to update the product description to 'funky top'', or 'I want to edit a product's description'"
To be honest, it is all quite pedantic.  I originally moved to change methods to avoid EF firing off unnecessary code during the binding process and I think this is as good a reason as any!

**Comment by dibley1973** [comment]
I am not sure if the customer would say 'I want to edit a product's description', either... Maybe more 'I want to _change_ a product's description'

Eitherway I am a fan of **private fields**, **public getters**, **private setters**, and **methods to mutate** the data, going forward.

I will investigate the backing state object a little further once I get time. I haven't got it in this code base, but have it elsewhere but have been getting in a mess. One of the plus sides is the state object can be very close to your database row and EF can access the state object public auto implemented properties how ever it likes. Like Joseph, I believe that if the data has come from the DB / datastore it should already be in a valid state, so we do not need to apply validation. If the data in the store is not valid we have bigger problems.

With the state I also quite like the idea of the Entity taking the state in one of the constructor overloads and also having a ToState() methods...

`public class MyEntity
{
    private MyEntityState _state;

    private MyEntity()
    {
        _state = new MyEntityState();
    }

    public MyEntity(string name) : this()
    {
        Guard.ArgumentIsNotNullOrWhiteSpace(state, "state");

        _state.Name = name;
    }

    public MyEntity(MyEntityState state)
    {
        Guard.ArgumentIsNotNull(state, "state");

        _state = state;
    }
}

public class MyEntityState
{
    internal string Name { get ; set; }
}`

DISCLAIMER: Code not written in VS so maybe wrong!

**Comment by dibley1973** [comment]
Probably should deep copy the state object before returning it in `ToState()`

**Comment by jadjare** [comment]
Just to note, none of the method names I used in my examples were supposed to imply they were right for Product Management, they were just examples off the top of my head.  Ultimately if method names are used refactoring will be cinch!!

**Comment by johncollinson2001** [comment]
Once again guys, agree with everything you've said! Will go with that convention from now forwards.

Joe - "_I originally moved to change methods to avoid EF firing off unnecessary code during the binding process and I think this is as good a reason as any!_"

Good call.

**Comment by johncollinson2001** [comment]
Agreed to use methods rather than property setters.
