### ISSUE TITLE
.Net Core, a limiting factor?

### ISSUE THREAD

**Issue by dibley1973** [dibley1973/OpenRMS#15]
I was following through the domains events section of [this Pluralsight course](https://app.pluralsight.com/library/courses/domain-driven-design-in-practice/table-of-contents) again and have discovered when trying to create the `DomainEvents` class that many of the object models that we take for granted in normal .Net are still not available in .Net Core. For example the `Type` classes method `GetInterfaces()`.

I cannot complete my class now because there is actually no (easy) way to find the assemblies that implement the right interface!

    public static class DomainEvents
    {
        private static List<Type> _staticHandlers;

        static DomainEvents()
        {
            var currentType = typeof(DomainEvents);
            var currentTypeInfo = currentType.GetTypeInfo();
            var assembly = currentTypeInfo.Assembly;
            var typesInAssembly = assembly.GetTypes();

            // When .Net core allows!
            //_staticHandlers = typesInAssembly
                //.Where(type => type.GetInterfaces().Any(type2 => type.IsGenericInterface && type2.GetGenericTypedefinition ==))
        }

        public static void Dispatch<TEvent>(TEvent domainEvent)
            where TEvent : IDomainEvent
        {
            foreach (Type staticHandler in _staticHandlers)
            {
                // When .Net core allows!
                //if (typeof(IDomainEventHandler<TEvent>).IsAssignableFrom(staticHandler))
                //{
                //    IDomainEventHandler<TEvent> instance =
                //        (IDomainEventHandler<TEvent>) Activator.CreateInstance(staticHandler);
                //}
            }
        }
    }

Can any of you bright sparks work out a way to do it with what we have at our hands?

**Comment by dibley1973** [comment]
John, not sure if you are able to get on **PluralSight** at the moment but when you can the course is very good. The guy has an interesting slant on how a lot of developers do `Domain Events` incorrectly, and events should actually live on the `AggregateRoot` until dispatched.

**Comment by jadjare** [comment]
@dibley1973 not sure if this Vernon Vaughn sample will help

https://github.com/VaughnVernon/IDDD_Samples_NET/blob/master/iddd_common/Domain.Model/DomainEventPublisher.cs

Seems simpler on the surface of things.

That said, I expect you're only playing with ideas so that's cool, but we do have to be careful to let things such as domain events reveal their need rather than just implement them incase they're useful.  However, as I said, I expect you're just playing with ideas and concepts... So play away and see where you get.

**Comment by dibley1973** [comment]
@jadjare  - Yes just having a play to see what it would take, mainly to make sure we don't back ourselves into a corner to early on. Will check out that link.

**Comment by dibley1973** [comment]
@jadjare  -  I may be wrong but Vaughan's version does seem to echo the "classic" way in the PS video. The author of the video does advise why this is not optimal. The reason for this is because it does not correctly follow the unit of work.

Say for instance a user changes the name and description of an entity via the UI. First the service calls calls `ChangeDescription` method on the entity and the `DescriptionChanged` event for it is raised. A subscriber handles the event and logs this to the event log. Then the service calls the `ChangeName` method on the entity, but this fails validation so no event is raised as the value was not changed. There is now no way of rolling back the processing that was carried out by subscribers of the 'DescriptionChanged' event.

Therefore the two changed events should only be raised when the unit of work completes, for example after the entity is successfully persisted back to the data store. This means the events should be stored on the aggregate root until the entity is persisted. Then they can be raised, and then cleared from teh aggregate root.

The example in the PS video makes my jumble of words a lot clearer! :)

**Comment by jadjare** [comment]
Fascinating, nothing's ever simple!. I'll have to take a look at the course, but your argument makes sense.

**Comment by johncollinson2001** [comment]
Howdy,

How about the solution in this post? http://udidahan.com/2009/06/14/domain-events-salvation/

It requires handlers to register their interest, rather than simply implement an interface, but that's not too bad? From a brief look I don't think it will run into the .NET core problems which you're seeing in the PS solution?

**Comment by dibley1973** [comment]
Looks good but I don't think that has a mechanism for saving up all events for one entity and only sending them when an entity's mutation is complete and persisted. We'd still have the problem the second action performed on an entity in a chain of actions failed the event for the first action would already have been sent out to subscribers so there is no rollback machanism. Unless I have mis understood the code of course. Which is entirely possible!

Also I did notice he passed the domain `Customer` entity back in one of the events. I have read this is bad practice and only **simple** data types should be carried in events.

**Comment by johncollinson2001** [comment]
Agreed to persevere with .NET core.
