### ISSUE TITLE
SQL Data Access base classes?

### ISSUE THREAD

**Issue by johncollinson2001** [dibley1973/OpenRMS#16]
Just wondered your thoughts.. if you pull/checkout develop right now you'll see there's a PostgreSql db context. The context code is pretty much generic for any database that EF connect to (apart from one line which adds a postgres extension to support Guid columns).

There is similar code in the unit of work classes.

Should this code be pulled out into a "shared infrastructure" project? Would this project be in the shared kernel?

**Comment by jadjare** [comment]
Which code is similar in the unit of work classes? I'm struggling to see it!

I personally think we should avoid trying to genericise everything at the first chance, it often leads to needless complexity.  If I recall correctly from the Mark Seaman course of SOLID development, he suggests a rule of 3, which stipulates you don't even look to genericise until at least 3 occurrences of the same are seen.

**Comment by dibley1973** [comment]
I will try and pull the code this morning and have a look.

RE: Mark's rule - I had forgotten that I think I really need to start applying that as I too do like genericism a bit too much!.

**Comment by dibley1973** [comment]
Reviewed the postgress DB access and it all looks nice, clean and straight forward to me, and loving the use of the `Maybe<... , ...>` I'm wondering if I can clean up the `Maybe` a little further so if it is constructed with a null parameter, it **does not** throw an exception for null parameter, but actually just understands it is to be a `Maybe<... , ...>` with no value. 

        public Maybe(TEntity entity)
        {
            _entity = entity;
        }

That would allow even simpler code in the repository.. What do you think?

        /// <summary>
        /// Gets the product with a name matching that supplied.
        /// </summary>
        /// <param name="name">The name of the product that is required.</param>
        /// <returns>A product with the specified name if found.</returns>
        public Maybe<Product, Guid> GetForName(string name)
        {
            var product = _context.Set<Product>().SingleOrDefault(p => p.Name == name);

            return new Maybe<Product, Guid>(product);
        }

Even if we do trim everything down do bare minimum (as per @jadjare other discussion) I think this example should stay in either a `develop-prototype` or `develope-examples` branch for future reference. Is every one happy with that?

Any better ideas. But remember my memory is pretty terrible so would like the example to be somewhere.

**Comment by johncollinson2001** [comment]
I think for the unit of work stuff, i was thinking some generic thing that took in a "SqlDbContext", which called save, which sub classes that had the specific repositories for the bounded context in them.

Rule of 3 sounds very good though, lets roll with that.

Duanes Maybe<> change sounds good too, think that went through my head as I typed out the inline IF to create the maybe which is now not necessary!

**Comment by johncollinson2001** [comment]
Closed
