### ISSUE TITLE
Simplify code base until necessity deems otherwise

### ISSUE THREAD

**Issue by jadjare** [dibley1973/OpenRMS#17]
I think we're all (including me) creating a large amount of complexity within the code base before we truly know we need it.  A lot of this is around playing with concept and theory, such as Domain Events, assumed base classes, interfaces, CQRS, etc.  It may be that I'm not keeping up with the pace of things, however, given the underlying simplicity of the problem, i.e. represent a "Product", be able to uniquely identify it and assign it a name and description, it seems the size of the code base is disproportionately large.  Don't get me wrong, I think there are loads of good ideas flying around which will definitely serve us well.

Next time we meet up ,what do people think about taking a slight step back, and identifying what belongs in the project at this stage and which ideas should be introduced later.  Many of the articles and training courses I've viewed suggest you concentrate on modelling the problem in the domain and use unit tests to prove it works, then you layer on other concerns.

I'm not saying that we should stop prototyping ideas and theories, really just that the main development branch should only contain the minimum necessary for it to solve the current set of problems without boxing us in to a corner.

Not a problem if you disagree, what are your thoughts?

**Comment by dibley1973** [comment]
It's a very valid point. I know from my own mind it's because I enjoy the challenge of wiring abstract concepts together and the problems they create.

I do agree that maybe we should branch the current code into a new branch maybe called "develope-prototying" so it is still there for reference and playing with as I would not want to loose what we have tried so far.

Then do as you say, @jadjare , and simplify the code to just model the problem and test with unit tests.

**Comment by johncollinson2001** [comment]
It's a good point. 

The CQRS stuff is defo overkill if you look at the code right now and I'm not 100% whether we'll need to do it or not (which suggests don't do it yet). Leave it in develop for the sec and we'll go through it when we catch up? We can look at putting it in a prototype branch or whatever, or just tag develop accordingly.

**Comment by dibley1973** [comment]
Well as long as our repositories have a well defined method for each query and only provide IEnumerable<T> not IQueryable<T> then I can live without CQRS until the EF performance becomes an apparent problem.

**Comment by jadjare** [comment]
I don't think there's any reason why a repository cannot call stored procedures directly on a database.  I don't believe it's a given that a repository must always utilise the chosen ORM tool for all interactions.  I believe it can mix and match is necessitated for performance, or any other, reason.

**Comment by dibley1973** [comment]
So based upon Vlad's suggestion which @jadjare's  wiki page links to should we remove the genericism of the ID from the base entity and just pick either a long integer or a Guid and stick with that until it becomes apparent that we need other DB Id types?

Also the linked blog post indicates that all DB Id types should ideally be the same type. I had it pictured that entities where it would not be an issue for a "hacker" to know guess an id could be some kind of interege, but for security concious entities a guid would be preferred.

Vaughan V also seems to suggest using a string Id,  but I've not read into that deeply enough as to why.

**Comment by dibley1973** [comment]
**Question:**  Should an entity be able to have it's ID changes after instantiation, or once and entity ID has be returned from the DB, should a new instance of the entity be spun up with the new ID and the original entity's property values?

**Comment by dibley1973** [comment]
A follow on from my question above. GetHashCode should only use immutable / readonly fields, this leads me to think that once an entity is constructed it's ID should not change. If we get a new ID back from the data store then we should create a new entity with it.

What are your thoughts?

**Comment by jadjare** [comment]
Thoughts:
**CQRS**
> Well as long as our repositories have a well defined method for each query and only provide IEnumerable not IQueryable then I can live without CQRS until the EF performance becomes an apparent problem

Just completed the bloody excellent DDD In Practice Pluralsight course by Vladimir Khorikov (thanks Duane for encouraging me to watch!)... At the end of the course he makes a brief mention of CQRS and gives a pointer to his blog post, illustrating different types.
http://enterprisecraftsmanship.com/2015/04/20/types-of-cqrs/  
Using his type definition we're assuming we need Type 2 at this stage.  I'm leaning towards a Type 1 implementation - which essentially means putting the queries in the repositories.  If the need for a Type 2 or 3 becomes apparent it shouldn't be too hard separate out the implementation from the Type 1 approach.

**ID Data Types**
> Also the linked blog post indicates that all DB Id types should ideally be the same type. I had it pictured that entities where it would not be an issue for a "hacker" to know guess an id could be some kind of interege, but for security concious entities a guid would be preferred.
I'm largely thinking that the choice of a GUID is the simplest solution for all entities at this stage.  If performance is an issue we'd have to tackle it later. However, GUID's are not memorable or easily readable and this creates an immediate problem in our domain.  I think that a product should have a "code" that is easily comprehended and memorable.  At present I thinking this will just be another field on a Product, possibly a value object or perhaps just a string.  I'm thinking this right now!! Perhaps the GUID Product.Id will be system generated, whilst the Product.Code value will be delegated to another service to create and in the first instance this might be a Hi/Lo Id generation technique.  This latter option opening up the possibility to use different product code generation techniques down the line.  We'll have a guaranteed unique Id for every product entity and an easily comprehendible Code.

**Other ID questions**
>Should an entity be able to have it's ID changes after instantiation, or once and entity ID has be returned from the DB, should a new instance of the entity be spun up with the new ID and the original entity's property values?

Where does the thought for this question come from?  I'm struggling to think why an entities ID would ever change.

>  If we get a new ID back from the data store then we should create a new entity with it.

Think I see where you're coming from now.... If we use a GUID this won't happen.  If we use an ID, I'm not sure I'd class changing an entities ID from 0 (aka "pending") to a integer value can be classed as changing an entity's ID.  Or am I missing the point!!

**Comment by dibley1973** [comment]
That is a good read. I am now definitely on board with starting with **Type 1** and moving to **Type 2** as and when performance or complexity demands.

So my thoughts on the entity depend upon if the domain creates the ID or the DB. If teh domein does in the case of a GUID or SHORTCODE, then the subject is moot. However if we let the DB do it we will have a "nullified" or "default" ID, passed to the DB, and after the record is created the new ID would be passed back up and either changed on the entity or a new entity created. I'd like to go for a new entity created so the ID can be immutable and marked with "readonly". This will help with GetHashCode for comparison operations in Dictionarys and such like.

What are your thoughts?

**Comment by dibley1973** [comment]
> Think I see where you're coming from now.... If we use a GUID this won't happen. If we use an ID, I'm not sure I'd class changing an entities ID from 0 (aka "pending") to a integer value can be classed as changing an entity's ID. Or am I missing the point!!

No not missing the point from a domain perspective more from an actual implementation perspective... and yes I guess we should not let coding Dr Resharper affect our domain decisions, but he does advise that GetHashcode only uses readonly fields to build the hashcode

**Comment by jadjare** [comment]
>However if we let the DB do it we will have a "nullified" or "default" ID, passed to the DB, and after the record is created the new ID would be passed back up and either changed on the entity or a new entity created. I'd like to go for a new entity created so the ID can be immutable and marked with "readonly". 

Ah, I think I can picture what you're talking about.   Have you tried the C#6 feature of auto implemented readonly properties? e.g. `public Id {get;}` 
https://msdn.microsoft.com/en-gb/magazine/dn802602.aspx
Based on the advise here it should make it a readonly, immutable, property that can still be bound.

I've updated the definition of the Entity.Id as follows
```
       /// <summary>
        /// Gets the identity for the entity
        /// </summary>
        public TId Id { get;  }
```
...and rebuild the project without errors.  Unfortunately I can't run it up at the moment to 100% confirm EF can complete the binding as I don't have the Vagrant thingy or Postgres db up at the moment - but that's a different conversation

**Comment by dibley1973** [comment]
My postgress Db does not work either but I have been banging in units test in the develop branch so feel free to run them on your changes..?

**Comment by johncollinson2001** [comment]
Agreed to abide by YAGNI as much as possible.
