### ISSUE TITLE
Product doesn't represent what it is?

### ISSUE THREAD

**Issue by jadjare** [dibley1973/OpenRMS#21]
I've been looking at the current Product implementation and wonder whether it models the problem correctly.  I'd welcome any thoughts on the points raised below.

I think when people talk about a Product they're referring to something a little higher level than our model presents.  For example, a pair of "Sports in-ear headphones with in-line remote" is the product, this product comes in a number of colour choices, "black", "white" and "gold".  

In essence I think a product consists of one or more Items.  A Product is a type of Item.  A Stock Keeping Unit consists of one or more Items.  Depending on how items are packed a product can be spread across one or more SKUs.  An Item can contain none, one, or more items.

In a real world example, this might play out something like this:
* Sports Headphones are a Product Item and comprise of 
 * Item 1: Black Headphones, contains two items
  * - Item 1.1: Headphones with black finish
  *  - Item 3: Standard Spare Ear Buds x 3 pack
 * Item 2: Gold Headphones
  * - Item 2.1 Headphones with gold finish
  * - Item 3: Standard Spare Ear Buds x 3 pack

* Standard Space Ear Buds x 3 pack, comprise of
 * Item 3: Standard Spare Ear Bugs x 3 pack, comprising of
  * - Item 3.1: Small
  * - Item 3.2: Medium
  * - Item 3.3: Large

This can be pretty simply modelled by changing our current Product definition to Item and adding a readonly collection of Items.

I also propose that ProductAttributes should be removed from the current Product class.  We don't need them yet and we've yet to suss out product attributes and how they will be managed.  Will they be an aggregate in their own right, how do they get associated to a product etc.

Thoughts....

**Comment by dibley1973** [comment]
Fair comments, well thought out, as ever @jadjare! I am happy for the change on both counts.

**Comment by johncollinson2001** [comment]
That was a great thought provoking read! 

I think you're right that what we have in the code right now is not a product. Item seems like a good name, and agree on the hierarchies of items - this effectively is our interpretation of Skus and packs? (Not wanting to cloud the blue sky thinking with RMS references!!)

I think of a product as something I can buy.

Think we might need to rename product management to item management.

**Comment by johncollinson2001** [comment]
Agreed to use the term item, with the concept of parent/child relationship between items.

**Comment by jadjare** [comment]
Added details of Item/Product description to glossary
