### ISSUE TITLE
Remove generic ID type support

### ISSUE THREAD

**Issue by johncollinson2001** [dibley1973/OpenRMS#26]
Remove generic ID type support, and change to a consistent type.

Suggested long or guid, I'm plumping for guid. This issue should not be started until this discussion point has been resolved.

Guid or long guys?

**Comment by jadjare** [comment]
Guid

**Comment by johncollinson2001** [comment]
Sorry Duane, it's already 2v1 :) 

Assigning to myself and cracking on with it....

**Comment by johncollinson2001** [comment]
Implemented in develop.
