### ISSUE TITLE
Feature: Ability to remove a location type from the system

### ISSUE THREAD

**Issue by dibley1973** [dibley1973/OpenRMS#3]
As a location administrator I want to be able to delete a location type from the system so that unused location types do not clutter the system.

It is acceptable when:

- I can remove a location type from the system if it is not in use
- I cannot remove a location type from the system if it is in use
- I cannot remove a location type from the system if it has ever been used (Not sure if this is a good idea?)

**Comment by johncollinson2001** [comment]
Pushed to dev
