### ISSUE TITLE
Feature: Ability to add new location into system

### ISSUE THREAD

**Issue by dibley1973** [dibley1973/OpenRMS#4]
As a location administrator I want to be able to add "locations" to the system so that I identifier within the system locations where product may be stored.

It is acceptable when:

- I can add a new location with a name of up to 50 characters
- I can add a code to uniquely identify each location
- I can add a description for the location to help identify it
- I can add a **Location Type** to the location 
- I cannot enter more than 25 characters for the unique identifier code 
- I cannot enter more than than 255 characters for a description 
- I cannot add a location with out a unique identifier code 
- I cannot add a location with out a name 
- I cannot add a location without setting it's **Location Type**

**Comment by johncollinson2001** [comment]
I'm going to progress this one. Can we discuss the acceptance criteria?

* In #2 I've raised that the issue should be abandoned. Therefore we should remove the concept of a location type entirely from the Location entity?
* Assuming no 50 char limit on the name?
* Assuming no 255 char limit on description?
* The unique code should operate in the same way as the item code? - I may create a base class of business code that we can use for all business entities?

**Comment by dibley1973** [comment]
I concur on the proposed revised acceptance criteria.

**Comment by johncollinson2001** [comment]
Location Management is currently an exact clone of Product Management! But at least we have a couple of contexts in the solution we can start to think about how they collaborate. I strongly think we need to catch up for an story writing session - no code.

**Comment by johncollinson2001** [comment]
Pushed to dev
