### ISSUE TITLE
Feature: Ability to edit an existing product in the system 

### ISSUE THREAD

**Issue by jadjare** [dibley1973/OpenRMS#7]
As a product administrator I want to be able to edit existing product details into the system so that I can alter the name of the product.

It is acceptable when:

- The unique identifier for the System ID does not change for the product
- I can change the Business ID of the product
- The changed Business ID does not need to be unique
- The Business ID must allow any characters
- The Business ID must contain at least one none white space character
- The product cannot be updated without a Business ID
- I can change the name of the product
- The changed name does not need to be unique
- The name must allow any characters
- The name must contain at least one none white space character
- The product cannot be updated without a name

**Comment by johncollinson2001** [comment]
Unit tests to be implemented on command handler

**Comment by johncollinson2001** [comment]
Implemented
