### ISSUE TITLE
Feature: Ability to delete product from the system

### ISSUE THREAD

**Issue by jadjare** [dibley1973/OpenRMS#9]
As a product administrator I want to be able to delete and existing product from the system so that it's no longer available to trade.

It is acceptable when:
- The product can no longer be recalled for use
- The System ID of the product is never reused even after deletion

**Comment by johncollinson2001** [comment]
Unit tests to be implemented on command handler

**Comment by dibley1973** [comment]
@jadjare & @johncollinson2001 - Need to discuss how we are intending to mark a `Item`as deleted.
Are we going for a flag like `IsDeleted` or `IsActive`, or are we going for a `Item` status where we can track the life-cycle of a product with something like:
```
public enum ItemStatus
{
    Proposed = 0,
    Active = 1,
    Obsolete = 2,
    Deleted = 3
}
```

**Comment by johncollinson2001** [comment]
Things should definitely be deletable in certain cases. Someone creates a product in error, we shouldnt hang on to that till the end of time. 

In your enum, if you remove the deleted status, and then said something like "products in a proposed state can be deleted" or something like that, I think that would be the best route forward.

**Comment by johncollinson2001** [comment]
I wouldn't worry about it too much at the mo though.. when the orders module or similar comes along, which requires a product to change state, then we'll naturally implement the rule then?

For now I'd leave products as deletable in all cases

**Comment by jadjare** [comment]
Remember YAGNI!!

I don't think there's any point in second guessing Item states at this point in time.  I say just mark it as Deleted with a Boolean flag for now.

**Comment by johncollinson2001** [comment]
@jadjare yes - I was suggesting permanent physical deletion for now (under the yagni banner)!

But not opposed to a deleted state, although I think simplest possible solution for right now...

**Comment by jadjare** [comment]
Cool, then I agree, let's just delete it completely.

@dibley1973 let us know if you disagree.

**Comment by dibley1973** [comment]
Ok, in that case if we are going for permanent physical deletion then I think this feature is complete. Feel free to review in the branch for this feature.

**Comment by dibley1973** [comment]
I Believe this feature to be complete
